<?php

declare(strict_types=1);

namespace KolayBi\UnitConverter\Units;

use KolayBi\UnitConverter\Contracts\Unit;
use KolayBi\UnitConverter\Enums\UnitCategory;

/**
 * Package types from UNECE Recommendation No. 21 (Rev. 12).
 *
 * Codes for types of cargo, packages and packaging materials used in
 * international trade. Per Rec 20 guidance, each 2-character Rec 21 code
 * is prefixed with 'X' to form a 3-character unit-of-measure code
 * (reserved range X00-XZZ).
 *
 * The native Rec 21 code (without X-prefix) is available as an alias
 * for resolution, but Rec 20 Packaging codes take priority when both
 * standards share the same code.
 *
 * @see https://unece.org/trade/uncefact/cl-recommendations
 */
enum PackageType: string implements Unit
{
    case DrumSteel = 'X1A';
    case DrumAluminium = 'X1B';
    case DrumPlywood = 'X1D';
    case ContainerFlexible = 'X1F';
    case DrumFibre = 'X1G';
    case DrumWooden = 'X1W';
    case BarrelWooden = 'X2C';
    case JerricanSteel = 'X3A';
    case JerricanPlastic = 'X3H';
    case BagSuperBulk = 'X43';
    case BagPolybag = 'X44';
    case BoxSteel = 'X4A';
    case BoxAluminium = 'X4B';
    case BoxNaturalWood = 'X4C';
    case BoxPlywood = 'X4D';
    case BoxReconstitutedWood = 'X4F';
    case BoxFibreboard = 'X4G';
    case BoxPlastic = 'X4H';
    case BagWovenPlastic = 'X5H';
    case BagTextile = 'X5L';
    case BagPaper = 'X5M';
    case CompositePackagingPlasticReceptacle = 'X6H';
    case CompositePackagingGlassReceptacle = 'X6P';
    case CaseCar = 'X7A';
    case CaseWooden = 'X7B';
    case PalletWooden = 'X8A';
    case CrateWooden = 'X8B';
    case BundleWooden = 'X8C';
    case IntermediateBulkContainerRigidPlastic = 'XAA';
    case ReceptacleFibre = 'XAB';
    case ReceptaclePaper = 'XAC';
    case ReceptacleWooden = 'XAD';
    case Aerosol = 'XAE';
    case PalletModularCollars80cmsX60cms = 'XAF';
    case PalletShrinkwrapped = 'XAG';
    case Pallet100cmsX110cms = 'XAH';
    case Clamshell = 'XAI';
    case Cone = 'XAJ';
    case Ball = 'XAL';
    case AmpouleNonProtected = 'XAM';
    case AmpouleProtected = 'XAP';
    case Atomizer = 'XAT';
    case Capsule = 'XAV';
    case Belt = 'XB4';
    case Barrel = 'XBA';
    case Bobbin = 'XBB';
    case BottlecrateOrBottlerack = 'XBC';
    case Board = 'XBD';
    case Bundle = 'XBE';
    case BalloonNonProtected = 'XBF';
    case Bag = 'XBG';
    case Bunch = 'XBH';
    case Bin = 'XBI';
    case Bucket = 'XBJ';
    case Basket = 'XBK';
    case BaleCompressed = 'XBL';
    case Basin = 'XBM';
    case BaleNonCompressed = 'XBN';
    case BottleNonProtectedCylindrical = 'XBO';
    case BalloonProtected = 'XBP';
    case BottleProtectedCylindrical = 'XBQ';
    case Bar = 'XBR';
    case BottleNonProtectedBulbous = 'XBS';
    case Bolt = 'XBT';
    case Butt = 'XBU';
    case BottleProtectedBulbous = 'XBV';
    case BoxForLiquids = 'XBW';
    case Box = 'XBX';
    case BoardInBundleOrbunchOrtruss = 'XBY';
    case BarsInBundleOrbunchOrtruss = 'XBZ';
    case CanRectangular = 'XCA';
    case CrateBeer = 'XCB';
    case Churn = 'XCC';
    case CanWithHandleAndSpout = 'XCD';
    case Creel = 'XCE';
    case Coffer = 'XCF';
    case Cage = 'XCG';
    case Chest = 'XCH';
    case Canister = 'XCI';
    case Coffin = 'XCJ';
    case Cask = 'XCK';
    case Coil = 'XCL';
    case Card = 'XCM';
    case ContainerNotOtherwiseSpecifiedAsTransportEquipment = 'XCN';
    case CarboyNonProtected = 'XCO';
    case CarboyProtected = 'XCP';
    case Cartridge = 'XCQ';
    case Crate = 'XCR';
    case Case = 'XCS';
    case Carton = 'XCT';
    case Cup = 'XCU';
    case Cover = 'XCV';
    case CageRoll = 'XCW';
    case CanCylindrical = 'XCX';
    case Cylinder = 'XCY';
    case Canvas = 'XCZ';
    case CrateMultipleLayerPlastic = 'XDA';
    case CrateMultipleLayerWooden = 'XDB';
    case CrateMultipleLayerCardboard = 'XDC';
    case CageCommonwealthHandlingEquipmentPool = 'XDG';
    case BoxCommonwealthHandlingEquipmentPoolEurobox = 'XDH';
    case DrumIron = 'XDI';
    case DemijohnNonProtected = 'XDJ';
    case CrateBulkCardboard = 'XDK';
    case CrateBulkPlastic = 'XDL';
    case CrateBulkWooden = 'XDM';
    case Dispenser = 'XDN';
    case DemijohnProtected = 'XDP';
    case Drum = 'XDR';
    case TrayOneLayerNoCoverPlastic = 'XDS';
    case TrayOneLayerNoCoverWooden = 'XDT';
    case TrayOneLayerNoCoverPolystyrene = 'XDU';
    case TrayOneLayerNoCoverCardboard = 'XDV';
    case TrayTwoLayersNoCoverPlasticTray = 'XDW';
    case TrayTwoLayersNoCoverWooden = 'XDX';
    case TrayTwoLayersNoCoverCardboard = 'XDY';
    case BagPlastic = 'XEC';
    case CaseWithPalletBase = 'XED';
    case CaseWithPalletBaseWooden = 'XEE';
    case CaseWithPalletBaseCardboard = 'XEF';
    case CaseWithPalletBasePlastic = 'XEG';
    case CaseWithPalletBaseMetal = 'XEH';
    case CaseIsothermic = 'XEI';
    case Envelope = 'XEN';
    case Flexibag = 'XFB';
    case CrateFruit = 'XFC';
    case CrateFramed = 'XFD';
    case Flexitank = 'XFE';
    case Firkin = 'XFI';
    case Flask = 'XFL';
    case Footlocker = 'XFO';
    case Filmpack = 'XFP';
    case Frame = 'XFR';
    case Foodtainer = 'XFT';
    case CartFlatbed = 'XFW';
    case BagFlexibleContainer = 'XFX';
    case BottleGas = 'XGB';
    case Girder = 'XGI';
    case ContainerGallon = 'XGL';
    case ReceptacleGlass = 'XGR';
    case TrayContainingHorizontallyStackedFlatItems = 'XGU';
    case BagGunny = 'XGY';
    case GirdersInBundleOrbunchOrtruss = 'XGZ';
    case BasketWithHandlePlastic = 'XHA';
    case BasketWithHandleWooden = 'XHB';
    case BasketWithHandleCardboard = 'XHC';
    case Hogshead = 'XHG';
    case Hanger = 'XHN';
    case Hamper = 'XHR';
    case PackageDisplayWooden = 'XIA';
    case PackageDisplayCardboard = 'XIB';
    case PackageDisplayPlastic = 'XIC';
    case PackageDisplayMetal = 'XID';
    case PackageShow = 'XIE';
    case PackageFlow = 'XIF';
    case PackagePaperWrapped = 'XIG';
    case DrumPlastic = 'XIH';
    case PackageCardboardWithBottleGripHoles = 'XIK';
    case TrayRigidLiddedStackable = 'XIL';
    case Ingot = 'XIN';
    case IngotsInBundleOrbunchOrtruss = 'XIZ';
    case BagJumbo = 'XJB';
    case JerricanRectangular = 'XJC';
    case Jug = 'XJG';
    case Jar = 'XJR';
    case Jutebag = 'XJT';
    case JerricanCylindrical = 'XJY';
    case Keg = 'XKG';
    case Kit = 'XKI';
    case Luggage = 'XLE';
    case Log = 'XLG';
    case Lot = 'XLT';
    case Lug = 'XLU';
    case Liftvan = 'XLV';
    case LogsInBundleOrbunchOrtruss = 'XLZ';
    case CrateMetal = 'XMA';
    case BagMultiply = 'XMB';
    case CrateMilk = 'XMC';
    case ContainerMetal = 'XME';
    case ReceptacleMetal = 'XMR';
    case SackMultiWall = 'XMS';
    case Mat = 'XMT';
    case ReceptaclePlasticWrapped = 'XMW';
    case Matchbox = 'XMX';
    case NotAvailable = 'XNA';
    case UnpackedOrUnpackaged = 'XNE';
    case UnpackedOrUnpackagedSingleUnit = 'XNF';
    case UnpackedOrUnpackagedMultipleUnits = 'XNG';
    case Nest = 'XNS';
    case Net = 'XNT';
    case NetTubePlastic = 'XNU';
    case NetTubeTextile = 'XNV';
    case PalletCHEP40CmX60Cm = 'XOA';
    case PalletCHEP80CmX120Cm = 'XOB';
    case PalletCHEP100CmX120Cm = 'XOC';

    /** @deprecated Marked for deletion in Rec 21 Rev 12. */
    case PalletAS40681993 = 'XOD';

    case PalletISOT11 = 'XOE';
    case PlatformUnspecifiedWeightOrDimension = 'XOF';
    case Block = 'XOK';
    case Octabin = 'XOT';
    case ContainerOuter = 'XOU';
    case PalletISO01Or2EUROPallet = 'XOG';
    case PalletISO11Or1EUROPallet = 'XOH';
    case PalletISO22Or1EUROPallet = 'XOI';
    case Size1Or4EUROPallet = 'XOJ';
    case Size1Or8EUROPallet = 'XOL';
    case SyntheticPalletISO1 = 'XOM';
    case SyntheticPalletISO2 = 'XON';
    case WholesalerPallet = 'XOP';
    case Pallet80X100Cm = 'XOQ';
    case Pallet60X100Cm = 'XOR';
    case OnewayPallet = 'XOS';
    case ReturnablePallet = 'XOV';
    case LargeBagPalletSized = 'XOW';
    case AWheeledPalletWithRaisedRim = 'XOX';
    case AWheeledPalletWithRaisedRimOY = 'XOY';
    case WheeledPalletWithRaisedRim = 'XOZ';
    case TwoSidedCageOnWheelsWithFixingStrap = 'XO1';
    case Trolley = 'XO2';
    case OnewayPalletISO01Or2EUROPallet = 'XO3';
    case OnewayPalletISO11Or1EUROPallet = 'XO4';
    case OnewayPalletISO22Or1EUROPallet = 'XO5';
    case PalletWithExceptionalDimensions = 'XO6';
    case WoodenPallet40CmX80Cm = 'XO7';
    case PlasticPalletSRS60CmX80Cm = 'XO8';
    case PlasticPalletSRS80CmX120Cm = 'XO9';
    case CHEPPallet60CmX80Cm = 'XP1';
    case LPRPallet60CmX80Cm = 'XP3';
    case LPRPallet80CmX120Cm = 'XP4';
    case Pan = 'XP2';
    case Packet = 'XPA';
    case PalletBoxCombinedOpenEndedBoxAndPallet = 'XPB';
    case Parcel = 'XPC';
    case PalletModularCollars80cmsX100cms = 'XPD';
    case PalletModularCollars80cmsX120cms = 'XPE';
    case Pen = 'XPF';
    case Plate = 'XPG';
    case Pitcher = 'XPH';
    case Pipe = 'XPI';
    case Punnet = 'XPJ';
    case Package = 'XPK';
    case Pail = 'XPL';
    case Plank = 'XPN';
    case Pouch = 'XPO';
    case Piece = 'XPP';
    case ReceptaclePlastic = 'XPR';
    case Pot = 'XPT';
    case Tray = 'XPU';
    case PipesInBundleOrbunchOrtruss = 'XPV';
    case Pallet = 'XPX';
    case PlatesInBundleOrbunchOrtruss = 'XPY';
    case PlanksInBundleOrbunchOrtruss = 'XPZ';
    case DrumSteelNonRemovableHead = 'XQA';
    case DrumSteelRemovableHead = 'XQB';
    case DrumAluminiumNonRemovableHead = 'XQC';
    case DrumAluminiumRemovableHead = 'XQD';
    case DrumPlasticNonRemovableHead = 'XQF';
    case DrumPlasticRemovableHead = 'XQG';
    case BarrelWoodenBungType = 'XQH';
    case BarrelWoodenRemovableHead = 'XQJ';
    case JerricanSteelNonRemovableHead = 'XQK';
    case JerricanSteelRemovableHead = 'XQL';
    case JerricanPlasticNonRemovableHead = 'XQM';
    case JerricanPlasticRemovableHead = 'XQN';
    case BoxWoodenNaturalWoodOrdinary = 'XQP';
    case BoxWoodenNaturalWoodWithSiftProofWalls = 'XQQ';
    case BoxPlasticExpanded = 'XQR';
    case BoxPlasticSolid = 'XQS';
    case Rod = 'XRD';
    case Ring = 'XRG';
    case RackClothingHanger = 'XRJ';
    case Rack = 'XRK';
    case Reel = 'XRL';
    case Roll = 'XRO';
    case Rednet = 'XRT';
    case RodsInBundleOrbunchOrtruss = 'XRZ';
    case Sack = 'XSA';
    case Slab = 'XSB';
    case CrateShallow = 'XSC';
    case Spindle = 'XSD';
    case SeaChest = 'XSE';
    case Sachet = 'XSH';
    case Skid = 'XSI';
    case CaseSkeleton = 'XSK';
    case Slipsheet = 'XSL';
    case Sheetmetal = 'XSM';
    case Spool = 'XSO';
    case SheetPlasticWrapping = 'XSP';
    case CaseSteel = 'XSS';
    case Sheet = 'XST';
    case Suitcase = 'XSU';
    case EnvelopeSteel = 'XSV';
    case Shrinkwrapped = 'XSW';

    /** @deprecated Marked for deletion in Rec 21 Rev 12. */
    case Set = 'XSX';

    case Sleeve = 'XSY';
    case SheetsInBundleOrbunchOrtruss = 'XSZ';
    case Tablet = 'XT1';
    case Tub = 'XTB';
    case TeaChest = 'XTC';
    case TubeCollapsible = 'XTD';
    case Tyre = 'XTE';
    case TankContainerGeneric = 'XTG';
    case Tierce = 'XTI';
    case TankRectangular = 'XTK';
    case TubWithLid = 'XTL';
    case Tin = 'XTN';
    case Tun = 'XTO';
    case Trunk = 'XTR';
    case Truss = 'XTS';
    case BagTote = 'XTT';
    case Tube = 'XTU';
    case TubeWithNozzle = 'XTV';
    case PalletTriwall = 'XTW';
    case TankCylindrical = 'XTY';
    case TubesInBundleOrbunchOrtruss = 'XTZ';
    case Uncaged = 'XUC';
    case Unit = 'XUN';
    case Vat = 'XVA';
    case BulkGas = 'XVG';
    case Vial = 'XVI';
    case Vanpack = 'XVK';
    case BulkLiquid = 'XVL';
    case BulkSolidLargeParticles = 'XVO';
    case VacuumPacked = 'XVP';
    case BulkLiquefiedGas = 'XVQ';
    case Vehicle = 'XVN';
    case BulkSolidGranularParticles = 'XVR';
    case BulkScrapMetal = 'XVS';
    case BulkSolidFineParticles = 'XVY';
    case IntermediateBulkContainer = 'XWA';
    case Wickerbottle = 'XWB';
    case IntermediateBulkContainerSteel = 'XWC';
    case IntermediateBulkContainerAluminium = 'XWD';
    case IntermediateBulkContainerMetal = 'XWF';
    case IntermediateBulkContainerSteelPressurisedOver10Kpa = 'XWG';
    case IntermediateBulkContainerAluminiumPressurisedOver10Kpa = 'XWH';
    case IntermediateBulkContainerMetalPressure10Kpa = 'XWJ';
    case IntermediateBulkContainerSteelLiquid = 'XWK';
    case IntermediateBulkContainerAluminiumLiquid = 'XWL';
    case IntermediateBulkContainerMetalLiquid = 'XWM';
    case IntermediateBulkContainerWovenPlasticWithoutCoatOrliner = 'XWN';
    case IntermediateBulkContainerWovenPlasticCoated = 'XWP';
    case IntermediateBulkContainerWovenPlasticWithLiner = 'XWQ';
    case IntermediateBulkContainerWovenPlasticCoatedAndLiner = 'XWR';
    case IntermediateBulkContainerPlasticFilm = 'XWS';
    case IntermediateBulkContainerTextileWithOutCoatOrliner = 'XWT';
    case IntermediateBulkContainerNaturalWoodWithInnerLiner = 'XWU';
    case IntermediateBulkContainerTextileCoated = 'XWV';
    case IntermediateBulkContainerTextileWithLiner = 'XWW';
    case IntermediateBulkContainerTextileCoatedAndLiner = 'XWX';
    case IntermediateBulkContainerPlywoodWithInnerLiner = 'XWY';
    case IntermediateBulkContainerReconstitutedWoodWithInnerLiner = 'XWZ';
    case BagWovenPlasticWithoutInnerCoatOrliner = 'XXA';
    case BagWovenPlasticSiftProof = 'XXB';
    case BagWovenPlasticWaterResistant = 'XXC';
    case BagPlasticsFilm = 'XXD';
    case BagTextileWithoutInnerCoatOrliner = 'XXF';
    case BagTextileSiftProof = 'XXG';
    case BagTextileWaterResistant = 'XXH';
    case BagPaperMultiWall = 'XXJ';
    case BagPaperMultiWallWaterResistant = 'XXK';
    case CompositePackagingPlasticReceptacleInSteelDrum = 'XYA';
    case CompositePackagingPlasticReceptacleInSteelCrateBox = 'XYB';
    case CompositePackagingPlasticReceptacleInAluminiumDrum = 'XYC';
    case CompositePackagingPlasticReceptacleInAluminiumCrate = 'XYD';
    case CompositePackagingPlasticReceptacleInWoodenBox = 'XYF';
    case CompositePackagingPlasticReceptacleInPlywoodDrum = 'XYG';
    case CompositePackagingPlasticReceptacleInPlywoodBox = 'XYH';
    case CompositePackagingPlasticReceptacleInFibreDrum = 'XYJ';
    case CompositePackagingPlasticReceptacleInFibreboardBox = 'XYK';
    case CompositePackagingPlasticReceptacleInPlasticDrum = 'XYL';
    case CompositePackagingPlasticReceptacleInSolidPlasticBox = 'XYM';
    case CompositePackagingGlassReceptacleInSteelDrum = 'XYN';
    case CompositePackagingGlassReceptacleInSteelCrateBox = 'XYP';
    case CompositePackagingGlassReceptacleInAluminiumDrum = 'XYQ';
    case CompositePackagingGlassReceptacleInAluminiumCrate = 'XYR';
    case CompositePackagingGlassReceptacleInWoodenBox = 'XYS';
    case CompositePackagingGlassReceptacleInPlywoodDrum = 'XYT';
    case CompositePackagingGlassReceptacleInWickerworkHamper = 'XYV';
    case CompositePackagingGlassReceptacleInFibreDrum = 'XYW';
    case CompositePackagingGlassReceptacleInFibreboardBox = 'XYX';
    case CompositePackagingGlassReceptacleInExpandablePlasticPack = 'XYY';
    case CompositePackagingGlassReceptacleInSolidPlasticPack = 'XYZ';
    case IntermediateBulkContainerPaperMultiWall = 'XZA';
    case BagLarge = 'XZB';
    case IntermediateBulkContainerPaperMultiWallWaterResistant = 'XZC';
    case IntermediateBulkContainerRigidPlasticWithStructuralEquipmentSolids = 'XZD';
    case IntermediateBulkContainerRigidPlasticFreestandingSolids = 'XZF';
    case IntermediateBulkContainerRigidPlasticWithStructuralEquipmentPressurised = 'XZG';
    case IntermediateBulkContainerRigidPlasticFreestandingPressurised = 'XZH';
    case IntermediateBulkContainerRigidPlasticWithStructuralEquipmentLiquids = 'XZJ';
    case IntermediateBulkContainerRigidPlasticFreestandingLiquids = 'XZK';
    case IntermediateBulkContainerCompositeRigidPlasticSolids = 'XZL';
    case IntermediateBulkContainerCompositeFlexiblePlasticSolids = 'XZM';
    case IntermediateBulkContainerCompositeRigidPlasticPressurised = 'XZN';
    case IntermediateBulkContainerCompositeFlexiblePlasticPressurised = 'XZP';
    case IntermediateBulkContainerCompositeRigidPlasticLiquids = 'XZQ';
    case IntermediateBulkContainerCompositeFlexiblePlasticLiquids = 'XZR';
    case IntermediateBulkContainerComposite = 'XZS';
    case IntermediateBulkContainerFibreboard = 'XZT';
    case IntermediateBulkContainerFlexible = 'XZU';
    case IntermediateBulkContainerMetalOtherThanSteel = 'XZV';
    case IntermediateBulkContainerNaturalWood = 'XZW';
    case IntermediateBulkContainerPlywood = 'XZX';
    case IntermediateBulkContainerReconstitutedWood = 'XZY';
    case MutuallyDefined = 'XZZ';

    public function code(): string
    {
        return $this->value;
    }

    public function symbol(): string
    {
        return $this->value;
    }

    public function label(): string
    {
        return match ($this) {
            self::DrumSteel                                                               => 'drum, steel',
            self::DrumAluminium                                                           => 'drum, aluminium',
            self::DrumPlywood                                                             => 'drum, plywood',
            self::ContainerFlexible                                                       => 'container, flexible',
            self::DrumFibre                                                               => 'drum, fibre',
            self::DrumWooden                                                              => 'drum, wooden',
            self::BarrelWooden                                                            => 'barrel, wooden',
            self::JerricanSteel                                                           => 'jerrican, steel',
            self::JerricanPlastic                                                         => 'jerrican, plastic',
            self::BagSuperBulk                                                            => 'bag, super bulk',
            self::BagPolybag                                                              => 'bag, polybag',
            self::BoxSteel                                                                => 'box, steel',
            self::BoxAluminium                                                            => 'box, aluminium',
            self::BoxNaturalWood                                                          => 'box, natural wood',
            self::BoxPlywood                                                              => 'box, plywood',
            self::BoxReconstitutedWood                                                    => 'box, reconstituted wood',
            self::BoxFibreboard                                                           => 'box, fibreboard',
            self::BoxPlastic                                                              => 'box, plastic',
            self::BagWovenPlastic                                                         => 'bag, woven plastic',
            self::BagTextile                                                              => 'bag, textile',
            self::BagPaper                                                                => 'bag, paper',
            self::CompositePackagingPlasticReceptacle                                     => 'composite packaging, plastic receptacle',
            self::CompositePackagingGlassReceptacle                                       => 'composite packaging, glass receptacle',
            self::CaseCar                                                                 => 'case, car',
            self::CaseWooden                                                              => 'case, wooden',
            self::PalletWooden                                                            => 'pallet, wooden',
            self::CrateWooden                                                             => 'crate, wooden',
            self::BundleWooden                                                            => 'bundle, wooden',
            self::IntermediateBulkContainerRigidPlastic                                   => 'intermediate bulk container, rigid plastic',
            self::ReceptacleFibre                                                         => 'receptacle, fibre',
            self::ReceptaclePaper                                                         => 'receptacle, paper',
            self::ReceptacleWooden                                                        => 'receptacle, wooden',
            self::Aerosol                                                                 => 'aerosol',
            self::PalletModularCollars80cmsX60cms                                         => 'pallet, modular, collars 80cms * 60cms',
            self::PalletShrinkwrapped                                                     => 'pallet, shrinkwrapped',
            self::Pallet100cmsX110cms                                                     => 'pallet, 100cms * 110cms',
            self::Clamshell                                                               => 'clamshell',
            self::Cone                                                                    => 'cone',
            self::Ball                                                                    => 'ball',
            self::AmpouleNonProtected                                                     => 'ampoule, non-protected',
            self::AmpouleProtected                                                        => 'ampoule, protected',
            self::Atomizer                                                                => 'atomizer',
            self::Capsule                                                                 => 'capsule',
            self::Belt                                                                    => 'belt',
            self::Barrel                                                                  => 'barrel',
            self::Bobbin                                                                  => 'bobbin',
            self::BottlecrateOrBottlerack                                                 => 'bottlecrate / bottlerack',
            self::Board                                                                   => 'board',
            self::Bundle                                                                  => 'bundle',
            self::BalloonNonProtected                                                     => 'balloon, non-protected',
            self::Bag                                                                     => 'bag',
            self::Bunch                                                                   => 'bunch',
            self::Bin                                                                     => 'bin',
            self::Bucket                                                                  => 'bucket',
            self::Basket                                                                  => 'basket',
            self::BaleCompressed                                                          => 'bale, compressed',
            self::Basin                                                                   => 'basin',
            self::BaleNonCompressed                                                       => 'bale, non-compressed',
            self::BottleNonProtectedCylindrical                                           => 'bottle, non-protected, cylindrical',
            self::BalloonProtected                                                        => 'balloon, protected',
            self::BottleProtectedCylindrical                                              => 'bottle, protected cylindrical',
            self::Bar                                                                     => 'bar',
            self::BottleNonProtectedBulbous                                               => 'bottle, non-protected, bulbous',
            self::Bolt                                                                    => 'bolt',
            self::Butt                                                                    => 'butt',
            self::BottleProtectedBulbous                                                  => 'bottle, protected bulbous',
            self::BoxForLiquids                                                           => 'box, for liquids',
            self::Box                                                                     => 'box',
            self::BoardInBundleOrbunchOrtruss                                             => 'board, in bundle/bunch/truss',
            self::BarsInBundleOrbunchOrtruss                                              => 'bars, in bundle/bunch/truss',
            self::CanRectangular                                                          => 'can, rectangular',
            self::CrateBeer                                                               => 'crate, beer',
            self::Churn                                                                   => 'churn',
            self::CanWithHandleAndSpout                                                   => 'can, with handle and spout',
            self::Creel                                                                   => 'creel',
            self::Coffer                                                                  => 'coffer',
            self::Cage                                                                    => 'cage',
            self::Chest                                                                   => 'chest',
            self::Canister                                                                => 'canister',
            self::Coffin                                                                  => 'coffin',
            self::Cask                                                                    => 'cask',
            self::Coil                                                                    => 'coil',
            self::Card                                                                    => 'card',
            self::ContainerNotOtherwiseSpecifiedAsTransportEquipment                      => 'container, not otherwise specified as transport equipment',
            self::CarboyNonProtected                                                      => 'carboy, non-protected',
            self::CarboyProtected                                                         => 'carboy, protected',
            self::Cartridge                                                               => 'cartridge',
            self::Crate                                                                   => 'crate',
            self::Case                                                                    => 'case',
            self::Carton                                                                  => 'carton',
            self::Cup                                                                     => 'cup',
            self::Cover                                                                   => 'cover',
            self::CageRoll                                                                => 'cage, roll',
            self::CanCylindrical                                                          => 'can, cylindrical',
            self::Cylinder                                                                => 'cylinder',
            self::Canvas                                                                  => 'canvas',
            self::CrateMultipleLayerPlastic                                               => 'crate, multiple layer, plastic',
            self::CrateMultipleLayerWooden                                                => 'crate, multiple layer, wooden',
            self::CrateMultipleLayerCardboard                                             => 'crate, multiple layer, cardboard',
            self::CageCommonwealthHandlingEquipmentPool                                   => 'cage, commonwealth handling equipment pool  (chep)',
            self::BoxCommonwealthHandlingEquipmentPoolEurobox                             => 'box, commonwealth handling equipment pool (chep), eurobox',
            self::DrumIron                                                                => 'drum, iron',
            self::DemijohnNonProtected                                                    => 'demijohn, non-protected',
            self::CrateBulkCardboard                                                      => 'crate, bulk, cardboard',
            self::CrateBulkPlastic                                                        => 'crate, bulk, plastic',
            self::CrateBulkWooden                                                         => 'crate, bulk, wooden',
            self::Dispenser                                                               => 'dispenser',
            self::DemijohnProtected                                                       => 'demijohn, protected',
            self::Drum                                                                    => 'drum',
            self::TrayOneLayerNoCoverPlastic                                              => 'tray, one layer no cover, plastic',
            self::TrayOneLayerNoCoverWooden                                               => 'tray, one layer no cover, wooden',
            self::TrayOneLayerNoCoverPolystyrene                                          => 'tray, one layer no cover, polystyrene',
            self::TrayOneLayerNoCoverCardboard                                            => 'tray, one layer no cover, cardboard',
            self::TrayTwoLayersNoCoverPlasticTray                                         => 'tray, two layers no cover, plastic tray',
            self::TrayTwoLayersNoCoverWooden                                              => 'tray, two layers no cover, wooden',
            self::TrayTwoLayersNoCoverCardboard                                           => 'tray, two layers no cover, cardboard',
            self::BagPlastic                                                              => 'bag, plastic',
            self::CaseWithPalletBase                                                      => 'case, with pallet base',
            self::CaseWithPalletBaseWooden                                                => 'case, with pallet base, wooden',
            self::CaseWithPalletBaseCardboard                                             => 'case, with pallet base, cardboard',
            self::CaseWithPalletBasePlastic                                               => 'case, with pallet base, plastic',
            self::CaseWithPalletBaseMetal                                                 => 'case, with pallet base, metal',
            self::CaseIsothermic                                                          => 'case, isothermic',
            self::Envelope                                                                => 'envelope',
            self::Flexibag                                                                => 'flexibag',
            self::CrateFruit                                                              => 'crate, fruit',
            self::CrateFramed                                                             => 'crate, framed',
            self::Flexitank                                                               => 'flexitank',
            self::Firkin                                                                  => 'firkin',
            self::Flask                                                                   => 'flask',
            self::Footlocker                                                              => 'footlocker',
            self::Filmpack                                                                => 'filmpack',
            self::Frame                                                                   => 'frame',
            self::Foodtainer                                                              => 'foodtainer',
            self::CartFlatbed                                                             => 'cart, flatbed',
            self::BagFlexibleContainer                                                    => 'bag, flexible container',
            self::BottleGas                                                               => 'bottle, gas',
            self::Girder                                                                  => 'girder',
            self::ContainerGallon                                                         => 'container, gallon',
            self::ReceptacleGlass                                                         => 'receptacle, glass',
            self::TrayContainingHorizontallyStackedFlatItems                              => 'tray, containing horizontally stacked flat items',
            self::BagGunny                                                                => 'bag, gunny',
            self::GirdersInBundleOrbunchOrtruss                                           => 'girders, in bundle/bunch/truss',
            self::BasketWithHandlePlastic                                                 => 'basket, with handle, plastic',
            self::BasketWithHandleWooden                                                  => 'basket, with handle, wooden',
            self::BasketWithHandleCardboard                                               => 'basket, with handle, cardboard',
            self::Hogshead                                                                => 'hogshead',
            self::Hanger                                                                  => 'hanger',
            self::Hamper                                                                  => 'hamper',
            self::PackageDisplayWooden                                                    => 'package, display, wooden',
            self::PackageDisplayCardboard                                                 => 'package, display, cardboard',
            self::PackageDisplayPlastic                                                   => 'package, display, plastic',
            self::PackageDisplayMetal                                                     => 'package, display, metal',
            self::PackageShow                                                             => 'package, show',
            self::PackageFlow                                                             => 'package, flow',
            self::PackagePaperWrapped                                                     => 'package, paper wrapped',
            self::DrumPlastic                                                             => 'drum, plastic',
            self::PackageCardboardWithBottleGripHoles                                     => 'package, cardboard, with bottle grip-holes',
            self::TrayRigidLiddedStackable                                                => 'tray, rigid, lidded stackable (cen ts 14482:2002)',
            self::Ingot                                                                   => 'ingot',
            self::IngotsInBundleOrbunchOrtruss                                            => 'ingots, in bundle/bunch/truss',
            self::BagJumbo                                                                => 'bag, jumbo',
            self::JerricanRectangular                                                     => 'jerrican, rectangular',
            self::Jug                                                                     => 'jug',
            self::Jar                                                                     => 'jar',
            self::Jutebag                                                                 => 'jutebag',
            self::JerricanCylindrical                                                     => 'jerrican, cylindrical',
            self::Keg                                                                     => 'keg',
            self::Kit                                                                     => 'kit',
            self::Luggage                                                                 => 'luggage',
            self::Log                                                                     => 'log',
            self::Lot                                                                     => 'lot',
            self::Lug                                                                     => 'lug',
            self::Liftvan                                                                 => 'liftvan',
            self::LogsInBundleOrbunchOrtruss                                              => 'logs, in bundle/bunch/truss',
            self::CrateMetal                                                              => 'crate, metal',
            self::BagMultiply                                                             => 'bag, multiply',
            self::CrateMilk                                                               => 'crate, milk',
            self::ContainerMetal                                                          => 'container, metal',
            self::ReceptacleMetal                                                         => 'receptacle, metal',
            self::SackMultiWall                                                           => 'sack, multi-wall',
            self::Mat                                                                     => 'mat',
            self::ReceptaclePlasticWrapped                                                => 'receptacle, plastic wrapped',
            self::Matchbox                                                                => 'matchbox',
            self::NotAvailable                                                            => 'not available',
            self::UnpackedOrUnpackaged                                                    => 'unpacked or unpackaged',
            self::UnpackedOrUnpackagedSingleUnit                                          => 'unpacked or unpackaged, single unit',
            self::UnpackedOrUnpackagedMultipleUnits                                       => 'unpacked or unpackaged, multiple units',
            self::Nest                                                                    => 'nest',
            self::Net                                                                     => 'net',
            self::NetTubePlastic                                                          => 'net, tube, plastic',
            self::NetTubeTextile                                                          => 'net, tube, textile',
            self::PalletCHEP40CmX60Cm                                                     => 'pallet, chep 40 cm x 60 cm',
            self::PalletCHEP80CmX120Cm                                                    => 'pallet, chep 80 cm x 120 cm',
            self::PalletCHEP100CmX120Cm                                                   => 'pallet, chep 100 cm x 120 cm',
            self::PalletAS40681993                                                        => 'pallet, as 4068-1993',
            self::PalletISOT11                                                            => 'pallet, iso t11',
            self::PlatformUnspecifiedWeightOrDimension                                    => 'platform, unspecified weight or dimension',
            self::Block                                                                   => 'block',
            self::Octabin                                                                 => 'octabin',
            self::ContainerOuter                                                          => 'container, outer',
            self::PalletISO01Or2EUROPallet                                                => 'pallet iso 0 - 1/2 euro pallet',
            self::PalletISO11Or1EUROPallet                                                => 'pallet iso 1 - 1/1 euro pallet',
            self::PalletISO22Or1EUROPallet                                                => 'pallet iso 2 – 2/1 euro pallet',
            self::Size1Or4EUROPallet                                                      => '1/4 euro pallet',
            self::Size1Or8EUROPallet                                                      => '1/8 euro pallet',
            self::SyntheticPalletISO1                                                     => 'synthetic pallet iso 1',
            self::SyntheticPalletISO2                                                     => 'synthetic pallet iso 2',
            self::WholesalerPallet                                                        => 'wholesaler pallet',
            self::Pallet80X100Cm                                                          => 'pallet 80 x 100 cm',
            self::Pallet60X100Cm                                                          => 'pallet 60 x 100 cm',
            self::OnewayPallet                                                            => 'oneway pallet',
            self::ReturnablePallet                                                        => 'returnable pallet',
            self::LargeBagPalletSized                                                     => 'large bag, pallet sized',
            self::AWheeledPalletWithRaisedRim                                             => 'a wheeled pallet with raised rim (81 x 67 x 135)',
            self::AWheeledPalletWithRaisedRimOY                                           => 'a wheeled pallet with raised rim (81 x 72 x 135)',
            self::WheeledPalletWithRaisedRim                                              => 'wheeled pallet with raised rim ( 81 x 60 x 16)',
            self::TwoSidedCageOnWheelsWithFixingStrap                                     => 'two sided cage on wheels with fixing strap',
            self::Trolley                                                                 => 'trolley',
            self::OnewayPalletISO01Or2EUROPallet                                          => 'oneway pallet iso 0 - 1/2 euro pallet',
            self::OnewayPalletISO11Or1EUROPallet                                          => 'oneway pallet iso 1 - 1/1 euro pallet',
            self::OnewayPalletISO22Or1EUROPallet                                          => 'oneway pallet iso 2 - 2/1 euro pallet',
            self::PalletWithExceptionalDimensions                                         => 'pallet with exceptional dimensions',
            self::WoodenPallet40CmX80Cm                                                   => 'wooden pallet  40 cm x 80 cm',
            self::PlasticPalletSRS60CmX80Cm                                               => 'plastic pallet srs 60 cm x 80 cm',
            self::PlasticPalletSRS80CmX120Cm                                              => 'plastic pallet srs 80 cm x 120 cm',
            self::CHEPPallet60CmX80Cm                                                     => 'chep pallet 60 cm x 80 cm',
            self::LPRPallet60CmX80Cm                                                      => 'lpr pallet 60 cm x 80 cm',
            self::LPRPallet80CmX120Cm                                                     => 'lpr pallet 80 cm x 120 cm',
            self::Pan                                                                     => 'pan',
            self::Packet                                                                  => 'packet',
            self::PalletBoxCombinedOpenEndedBoxAndPallet                                  => 'pallet, box combined open-ended box and pallet',
            self::Parcel                                                                  => 'parcel',
            self::PalletModularCollars80cmsX100cms                                        => 'pallet, modular, collars 80cms * 100cms',
            self::PalletModularCollars80cmsX120cms                                        => 'pallet, modular, collars 80cms * 120cms',
            self::Pen                                                                     => 'pen',
            self::Plate                                                                   => 'plate',
            self::Pitcher                                                                 => 'pitcher',
            self::Pipe                                                                    => 'pipe',
            self::Punnet                                                                  => 'punnet',
            self::Package                                                                 => 'package',
            self::Pail                                                                    => 'pail',
            self::Plank                                                                   => 'plank',
            self::Pouch                                                                   => 'pouch',
            self::Piece                                                                   => 'piece',
            self::ReceptaclePlastic                                                       => 'receptacle, plastic',
            self::Pot                                                                     => 'pot',
            self::Tray                                                                    => 'tray',
            self::PipesInBundleOrbunchOrtruss                                             => 'pipes, in bundle/bunch/truss',
            self::Pallet                                                                  => 'pallet',
            self::PlatesInBundleOrbunchOrtruss                                            => 'plates, in bundle/bunch/truss',
            self::PlanksInBundleOrbunchOrtruss                                            => 'planks, in bundle/bunch/truss',
            self::DrumSteelNonRemovableHead                                               => 'drum, steel, non-removable head',
            self::DrumSteelRemovableHead                                                  => 'drum, steel, removable head',
            self::DrumAluminiumNonRemovableHead                                           => 'drum, aluminium, non-removable head',
            self::DrumAluminiumRemovableHead                                              => 'drum, aluminium, removable head',
            self::DrumPlasticNonRemovableHead                                             => 'drum, plastic, non-removable head',
            self::DrumPlasticRemovableHead                                                => 'drum, plastic, removable head',
            self::BarrelWoodenBungType                                                    => 'barrel, wooden, bung type',
            self::BarrelWoodenRemovableHead                                               => 'barrel, wooden, removable head',
            self::JerricanSteelNonRemovableHead                                           => 'jerrican, steel, non-removable head',
            self::JerricanSteelRemovableHead                                              => 'jerrican, steel, removable head',
            self::JerricanPlasticNonRemovableHead                                         => 'jerrican, plastic, non-removable head',
            self::JerricanPlasticRemovableHead                                            => 'jerrican, plastic, removable head',
            self::BoxWoodenNaturalWoodOrdinary                                            => 'box, wooden, natural wood, ordinary',
            self::BoxWoodenNaturalWoodWithSiftProofWalls                                  => 'box, wooden, natural wood, with sift proof walls',
            self::BoxPlasticExpanded                                                      => 'box, plastic, expanded',
            self::BoxPlasticSolid                                                         => 'box, plastic, solid',
            self::Rod                                                                     => 'rod',
            self::Ring                                                                    => 'ring',
            self::RackClothingHanger                                                      => 'rack, clothing hanger',
            self::Rack                                                                    => 'rack',
            self::Reel                                                                    => 'reel',
            self::Roll                                                                    => 'roll',
            self::Rednet                                                                  => 'rednet',
            self::RodsInBundleOrbunchOrtruss                                              => 'rods, in bundle/bunch/truss',
            self::Sack                                                                    => 'sack',
            self::Slab                                                                    => 'slab',
            self::CrateShallow                                                            => 'crate, shallow',
            self::Spindle                                                                 => 'spindle',
            self::SeaChest                                                                => 'sea-chest',
            self::Sachet                                                                  => 'sachet',
            self::Skid                                                                    => 'skid',
            self::CaseSkeleton                                                            => 'case, skeleton',
            self::Slipsheet                                                               => 'slipsheet',
            self::Sheetmetal                                                              => 'sheetmetal',
            self::Spool                                                                   => 'spool',
            self::SheetPlasticWrapping                                                    => 'sheet, plastic wrapping',
            self::CaseSteel                                                               => 'case, steel',
            self::Sheet                                                                   => 'sheet',
            self::Suitcase                                                                => 'suitcase',
            self::EnvelopeSteel                                                           => 'envelope, steel',
            self::Shrinkwrapped                                                           => 'shrinkwrapped',
            self::Set                                                                     => 'set',
            self::Sleeve                                                                  => 'sleeve',
            self::SheetsInBundleOrbunchOrtruss                                            => 'sheets, in bundle/bunch/truss',
            self::Tablet                                                                  => 'tablet',
            self::Tub                                                                     => 'tub',
            self::TeaChest                                                                => 'tea-chest',
            self::TubeCollapsible                                                         => 'tube, collapsible',
            self::Tyre                                                                    => 'tyre',
            self::TankContainerGeneric                                                    => 'tank container, generic',
            self::Tierce                                                                  => 'tierce',
            self::TankRectangular                                                         => 'tank, rectangular',
            self::TubWithLid                                                              => 'tub, with lid',
            self::Tin                                                                     => 'tin',
            self::Tun                                                                     => 'tun',
            self::Trunk                                                                   => 'trunk',
            self::Truss                                                                   => 'truss',
            self::BagTote                                                                 => 'bag, tote',
            self::Tube                                                                    => 'tube',
            self::TubeWithNozzle                                                          => 'tube, with nozzle',
            self::PalletTriwall                                                           => 'pallet, triwall',
            self::TankCylindrical                                                         => 'tank, cylindrical',
            self::TubesInBundleOrbunchOrtruss                                             => 'tubes, in bundle/bunch/truss',
            self::Uncaged                                                                 => 'uncaged',
            self::Unit                                                                    => 'unit',
            self::Vat                                                                     => 'vat',
            self::BulkGas                                                                 => 'bulk, gas (at 1031 mbar and 15°c)',
            self::Vial                                                                    => 'vial',
            self::Vanpack                                                                 => 'vanpack',
            self::BulkLiquid                                                              => 'bulk, liquid',
            self::BulkSolidLargeParticles                                                 => 'bulk, solid, large particles (“nodules”)',
            self::VacuumPacked                                                            => 'vacuum-packed',
            self::BulkLiquefiedGas                                                        => 'bulk, liquefied gas (at abnormal temperature/pressure)',
            self::Vehicle                                                                 => 'vehicle',
            self::BulkSolidGranularParticles                                              => 'bulk, solid, granular particles (“grains”)',
            self::BulkScrapMetal                                                          => 'bulk, scrap metal',
            self::BulkSolidFineParticles                                                  => 'bulk, solid, fine particles (“powders”)',
            self::IntermediateBulkContainer                                               => 'intermediate bulk container',
            self::Wickerbottle                                                            => 'wickerbottle',
            self::IntermediateBulkContainerSteel                                          => 'intermediate bulk container, steel',
            self::IntermediateBulkContainerAluminium                                      => 'intermediate bulk container, aluminium',
            self::IntermediateBulkContainerMetal                                          => 'intermediate bulk container, metal',
            self::IntermediateBulkContainerSteelPressurisedOver10Kpa                      => 'intermediate bulk container, steel, pressurised > 10 kpa',
            self::IntermediateBulkContainerAluminiumPressurisedOver10Kpa                  => 'intermediate bulk container, aluminium, pressurised > 10 kpa',
            self::IntermediateBulkContainerMetalPressure10Kpa                             => 'intermediate bulk container, metal, pressure 10 kpa',
            self::IntermediateBulkContainerSteelLiquid                                    => 'intermediate bulk container, steel, liquid',
            self::IntermediateBulkContainerAluminiumLiquid                                => 'intermediate bulk container, aluminium, liquid',
            self::IntermediateBulkContainerMetalLiquid                                    => 'intermediate bulk container, metal, liquid',
            self::IntermediateBulkContainerWovenPlasticWithoutCoatOrliner                 => 'intermediate bulk container, woven plastic, without coat/liner',
            self::IntermediateBulkContainerWovenPlasticCoated                             => 'intermediate bulk container, woven plastic, coated',
            self::IntermediateBulkContainerWovenPlasticWithLiner                          => 'intermediate bulk container, woven plastic, with liner',
            self::IntermediateBulkContainerWovenPlasticCoatedAndLiner                     => 'intermediate bulk container, woven plastic, coated and liner',
            self::IntermediateBulkContainerPlasticFilm                                    => 'intermediate bulk container, plastic film',
            self::IntermediateBulkContainerTextileWithOutCoatOrliner                      => 'intermediate bulk container, textile with out coat/liner',
            self::IntermediateBulkContainerNaturalWoodWithInnerLiner                      => 'intermediate bulk container, natural wood, with inner liner',
            self::IntermediateBulkContainerTextileCoated                                  => 'intermediate bulk container, textile, coated',
            self::IntermediateBulkContainerTextileWithLiner                               => 'intermediate bulk container, textile, with liner',
            self::IntermediateBulkContainerTextileCoatedAndLiner                          => 'intermediate bulk container, textile, coated and liner',
            self::IntermediateBulkContainerPlywoodWithInnerLiner                          => 'intermediate bulk container, plywood, with inner liner',
            self::IntermediateBulkContainerReconstitutedWoodWithInnerLiner                => 'intermediate bulk container, reconstituted wood, with inner liner',
            self::BagWovenPlasticWithoutInnerCoatOrliner                                  => 'bag, woven plastic, without inner coat/liner',
            self::BagWovenPlasticSiftProof                                                => 'bag, woven plastic, sift proof',
            self::BagWovenPlasticWaterResistant                                           => 'bag, woven plastic, water resistant',
            self::BagPlasticsFilm                                                         => 'bag, plastics film',
            self::BagTextileWithoutInnerCoatOrliner                                       => 'bag, textile, without inner coat/liner',
            self::BagTextileSiftProof                                                     => 'bag, textile, sift proof',
            self::BagTextileWaterResistant                                                => 'bag, textile, water resistant',
            self::BagPaperMultiWall                                                       => 'bag, paper, multi-wall',
            self::BagPaperMultiWallWaterResistant                                         => 'bag, paper, multi-wall, water resistant',
            self::CompositePackagingPlasticReceptacleInSteelDrum                          => 'composite packaging, plastic receptacle in steel drum',
            self::CompositePackagingPlasticReceptacleInSteelCrateBox                      => 'composite packaging, plastic receptacle in steel crate box',
            self::CompositePackagingPlasticReceptacleInAluminiumDrum                      => 'composite packaging, plastic receptacle in aluminium drum',
            self::CompositePackagingPlasticReceptacleInAluminiumCrate                     => 'composite packaging, plastic receptacle in aluminium crate',
            self::CompositePackagingPlasticReceptacleInWoodenBox                          => 'composite packaging, plastic receptacle in wooden box',
            self::CompositePackagingPlasticReceptacleInPlywoodDrum                        => 'composite packaging, plastic receptacle in plywood drum',
            self::CompositePackagingPlasticReceptacleInPlywoodBox                         => 'composite packaging, plastic receptacle in plywood box',
            self::CompositePackagingPlasticReceptacleInFibreDrum                          => 'composite packaging, plastic receptacle in fibre drum',
            self::CompositePackagingPlasticReceptacleInFibreboardBox                      => 'composite packaging, plastic receptacle in fibreboard box',
            self::CompositePackagingPlasticReceptacleInPlasticDrum                        => 'composite packaging, plastic receptacle in plastic drum',
            self::CompositePackagingPlasticReceptacleInSolidPlasticBox                    => 'composite packaging, plastic receptacle in solid plastic box',
            self::CompositePackagingGlassReceptacleInSteelDrum                            => 'composite packaging, glass receptacle in steel drum',
            self::CompositePackagingGlassReceptacleInSteelCrateBox                        => 'composite packaging, glass receptacle in steel crate box',
            self::CompositePackagingGlassReceptacleInAluminiumDrum                        => 'composite packaging, glass receptacle in aluminium drum',
            self::CompositePackagingGlassReceptacleInAluminiumCrate                       => 'composite packaging, glass receptacle in aluminium crate',
            self::CompositePackagingGlassReceptacleInWoodenBox                            => 'composite packaging, glass receptacle in wooden box',
            self::CompositePackagingGlassReceptacleInPlywoodDrum                          => 'composite packaging, glass receptacle in plywood drum',
            self::CompositePackagingGlassReceptacleInWickerworkHamper                     => 'composite packaging, glass receptacle in wickerwork hamper',
            self::CompositePackagingGlassReceptacleInFibreDrum                            => 'composite packaging, glass receptacle in fibre drum',
            self::CompositePackagingGlassReceptacleInFibreboardBox                        => 'composite packaging, glass receptacle in fibreboard box',
            self::CompositePackagingGlassReceptacleInExpandablePlasticPack                => 'composite packaging, glass receptacle in expandable plastic pack',
            self::CompositePackagingGlassReceptacleInSolidPlasticPack                     => 'composite packaging, glass receptacle in solid plastic pack',
            self::IntermediateBulkContainerPaperMultiWall                                 => 'intermediate bulk container, paper, multi-wall',
            self::BagLarge                                                                => 'bag, large',
            self::IntermediateBulkContainerPaperMultiWallWaterResistant                   => 'intermediate bulk container, paper, multi-wall, water resistant',
            self::IntermediateBulkContainerRigidPlasticWithStructuralEquipmentSolids      => 'intermediate bulk container, rigid plastic, with structural equipment, solids',
            self::IntermediateBulkContainerRigidPlasticFreestandingSolids                 => 'intermediate bulk container, rigid plastic, freestanding, solids',
            self::IntermediateBulkContainerRigidPlasticWithStructuralEquipmentPressurised => 'intermediate bulk container, rigid plastic, with structural equipment, pressurised',
            self::IntermediateBulkContainerRigidPlasticFreestandingPressurised            => 'intermediate bulk container, rigid plastic, freestanding, pressurised',
            self::IntermediateBulkContainerRigidPlasticWithStructuralEquipmentLiquids     => 'intermediate bulk container, rigid plastic, with structural equipment, liquids',
            self::IntermediateBulkContainerRigidPlasticFreestandingLiquids                => 'intermediate bulk container, rigid plastic, freestanding, liquids',
            self::IntermediateBulkContainerCompositeRigidPlasticSolids                    => 'intermediate bulk container, composite, rigid plastic, solids',
            self::IntermediateBulkContainerCompositeFlexiblePlasticSolids                 => 'intermediate bulk container, composite, flexible plastic, solids',
            self::IntermediateBulkContainerCompositeRigidPlasticPressurised               => 'intermediate bulk container, composite, rigid plastic, pressurised',
            self::IntermediateBulkContainerCompositeFlexiblePlasticPressurised            => 'intermediate bulk container, composite, flexible plastic, pressurised',
            self::IntermediateBulkContainerCompositeRigidPlasticLiquids                   => 'intermediate bulk container, composite, rigid plastic, liquids',
            self::IntermediateBulkContainerCompositeFlexiblePlasticLiquids                => 'intermediate bulk container, composite, flexible plastic, liquids',
            self::IntermediateBulkContainerComposite                                      => 'intermediate bulk container, composite',
            self::IntermediateBulkContainerFibreboard                                     => 'intermediate bulk container, fibreboard',
            self::IntermediateBulkContainerFlexible                                       => 'intermediate bulk container, flexible',
            self::IntermediateBulkContainerMetalOtherThanSteel                            => 'intermediate bulk container, metal, other than steel',
            self::IntermediateBulkContainerNaturalWood                                    => 'intermediate bulk container, natural wood',
            self::IntermediateBulkContainerPlywood                                        => 'intermediate bulk container, plywood',
            self::IntermediateBulkContainerReconstitutedWood                              => 'intermediate bulk container, reconstituted wood',
            self::MutuallyDefined                                                         => 'mutually defined',
        };
    }

    /**
     * Returns the native Rec 21 code (without X-prefix).
     */
    public function rec21Code(): string
    {
        return substr($this->value, 1);
    }

    /**
     * @return list<string>
     */
    public function aliases(): array
    {
        return [$this->value, $this->rec21Code(), $this->label()];
    }

    public function multiplier(): string
    {
        return '0';
    }

    public function offset(): string
    {
        return '0';
    }

    public function category(): UnitCategory
    {
        return UnitCategory::PackageType;
    }
}
